// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/max-marek-projects/shortener/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, info
func (_m *Storage) Add(ctx context.Context, info repository.Row) error {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Row) error); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Storage_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - info repository.Row
func (_e *Storage_Expecter) Add(ctx interface{}, info interface{}) *Storage_Add_Call {
	return &Storage_Add_Call{Call: _e.mock.On("Add", ctx, info)}
}

func (_c *Storage_Add_Call) Run(run func(ctx context.Context, info repository.Row)) *Storage_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.Row))
	})
	return _c
}

func (_c *Storage_Add_Call) Return(_a0 error) *Storage_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Add_Call) RunAndReturn(run func(context.Context, repository.Row) error) *Storage_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddBatch provides a mock function with given fields: ctx, items
func (_m *Storage) AddBatch(ctx context.Context, items []repository.Row) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.Row) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_AddBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBatch'
type Storage_AddBatch_Call struct {
	*mock.Call
}

// AddBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items []repository.Row
func (_e *Storage_Expecter) AddBatch(ctx interface{}, items interface{}) *Storage_AddBatch_Call {
	return &Storage_AddBatch_Call{Call: _e.mock.On("AddBatch", ctx, items)}
}

func (_c *Storage_AddBatch_Call) Run(run func(ctx context.Context, items []repository.Row)) *Storage_AddBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]repository.Row))
	})
	return _c
}

func (_c *Storage_AddBatch_Call) Return(_a0 error) *Storage_AddBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_AddBatch_Call) RunAndReturn(run func(context.Context, []repository.Row) error) *Storage_AddBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *Storage) Get(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Storage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Storage_Expecter) Get(ctx interface{}, id interface{}) *Storage_Get_Call {
	return &Storage_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Storage_Get_Call) Run(run func(ctx context.Context, id string)) *Storage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_Get_Call) Return(_a0 string, _a1 error) *Storage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Storage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function with given fields: ctx, userID
func (_m *Storage) GetUserURLs(ctx context.Context, userID string) ([]repository.UserURL, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []repository.UserURL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]repository.UserURL, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []repository.UserURL); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.UserURL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type Storage_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Storage_Expecter) GetUserURLs(ctx interface{}, userID interface{}) *Storage_GetUserURLs_Call {
	return &Storage_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, userID)}
}

func (_c *Storage_GetUserURLs_Call) Run(run func(ctx context.Context, userID string)) *Storage_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetUserURLs_Call) Return(_a0 []repository.UserURL, _a1 error) *Storage_GetUserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetUserURLs_Call) RunAndReturn(run func(context.Context, string) ([]repository.UserURL, error)) *Storage_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *Storage) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Storage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) Ping(ctx interface{}) *Storage_Ping_Call {
	return &Storage_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *Storage_Ping_Call) Run(run func(ctx context.Context)) *Storage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_Ping_Call) Return(_a0 error) *Storage_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Ping_Call) RunAndReturn(run func(context.Context) error) *Storage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
