// Code generated by mockery v2.53.6. DO NOT EDIT.

package audit

import (
	models "github.com/max-marek-projects/shortener/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver struct {
	mock.Mock
}

type MockObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObserver) EXPECT() *MockObserver_Expecter {
	return &MockObserver_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function with given fields: event
func (_m *MockObserver) Notify(event models.AuditEvent) {
	_m.Called(event)
}

// MockObserver_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockObserver_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - event models.AuditEvent
func (_e *MockObserver_Expecter) Notify(event interface{}) *MockObserver_Notify_Call {
	return &MockObserver_Notify_Call{Call: _e.mock.On("Notify", event)}
}

func (_c *MockObserver_Notify_Call) Run(run func(event models.AuditEvent)) *MockObserver_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.AuditEvent))
	})
	return _c
}

func (_c *MockObserver_Notify_Call) Return() *MockObserver_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObserver_Notify_Call) RunAndReturn(run func(models.AuditEvent)) *MockObserver_Notify_Call {
	_c.Run(run)
	return _c
}

// NewMockObserver creates a new instance of MockObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserver {
	mock := &MockObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
