// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	models "github.com/max-marek-projects/shortener/internal/models"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/max-marek-projects/shortener/internal/repository"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, info
func (_m *MockStorage) Add(ctx context.Context, info repository.Row) error {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Row) error); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockStorage_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - info repository.Row
func (_e *MockStorage_Expecter) Add(ctx interface{}, info interface{}) *MockStorage_Add_Call {
	return &MockStorage_Add_Call{Call: _e.mock.On("Add", ctx, info)}
}

func (_c *MockStorage_Add_Call) Run(run func(ctx context.Context, info repository.Row)) *MockStorage_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.Row))
	})
	return _c
}

func (_c *MockStorage_Add_Call) Return(_a0 error) *MockStorage_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Add_Call) RunAndReturn(run func(context.Context, repository.Row) error) *MockStorage_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddBatch provides a mock function with given fields: ctx, items
func (_m *MockStorage) AddBatch(ctx context.Context, items []repository.Row) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.Row) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_AddBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBatch'
type MockStorage_AddBatch_Call struct {
	*mock.Call
}

// AddBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items []repository.Row
func (_e *MockStorage_Expecter) AddBatch(ctx interface{}, items interface{}) *MockStorage_AddBatch_Call {
	return &MockStorage_AddBatch_Call{Call: _e.mock.On("AddBatch", ctx, items)}
}

func (_c *MockStorage_AddBatch_Call) Run(run func(ctx context.Context, items []repository.Row)) *MockStorage_AddBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]repository.Row))
	})
	return _c
}

func (_c *MockStorage_AddBatch_Call) Return(_a0 error) *MockStorage_AddBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_AddBatch_Call) RunAndReturn(run func(context.Context, []repository.Row) error) *MockStorage_AddBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBatch provides a mock function with given fields: ctx, userID, shortIDs
func (_m *MockStorage) DeleteBatch(ctx context.Context, userID string, shortIDs []string) error {
	ret := _m.Called(ctx, userID, shortIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, userID, shortIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type MockStorage_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - shortIDs []string
func (_e *MockStorage_Expecter) DeleteBatch(ctx interface{}, userID interface{}, shortIDs interface{}) *MockStorage_DeleteBatch_Call {
	return &MockStorage_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", ctx, userID, shortIDs)}
}

func (_c *MockStorage_DeleteBatch_Call) Run(run func(ctx context.Context, userID string, shortIDs []string)) *MockStorage_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockStorage_DeleteBatch_Call) Return(_a0 error) *MockStorage_DeleteBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteBatch_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockStorage_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockStorage) Get(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStorage_Expecter) Get(ctx interface{}, id interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, id string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(_a0 string, _a1 error) *MockStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockStorage) GetStats(ctx context.Context) (models.Statistics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 models.Statistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.Statistics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.Statistics); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.Statistics)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockStorage_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) GetStats(ctx interface{}) *MockStorage_GetStats_Call {
	return &MockStorage_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockStorage_GetStats_Call) Run(run func(ctx context.Context)) *MockStorage_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_GetStats_Call) Return(_a0 models.Statistics, _a1 error) *MockStorage_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetStats_Call) RunAndReturn(run func(context.Context) (models.Statistics, error)) *MockStorage_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function with given fields: ctx, userID
func (_m *MockStorage) GetUserURLs(ctx context.Context, userID string) ([]repository.UserURL, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []repository.UserURL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]repository.UserURL, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []repository.UserURL); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.UserURL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockStorage_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockStorage_Expecter) GetUserURLs(ctx interface{}, userID interface{}) *MockStorage_GetUserURLs_Call {
	return &MockStorage_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, userID)}
}

func (_c *MockStorage_GetUserURLs_Call) Run(run func(ctx context.Context, userID string)) *MockStorage_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetUserURLs_Call) Return(_a0 []repository.UserURL, _a1 error) *MockStorage_GetUserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetUserURLs_Call) RunAndReturn(run func(context.Context, string) ([]repository.UserURL, error)) *MockStorage_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockStorage) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Ping(ctx interface{}) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStorage_Ping_Call) Run(run func(ctx context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(_a0 error) *MockStorage_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
