// Code generated by mockery v2.53.6. DO NOT EDIT.

package middlewares

import (
	audit "github.com/max-marek-projects/shortener/internal/audit"
	mock "github.com/stretchr/testify/mock"

	models "github.com/max-marek-projects/shortener/internal/models"

	sync "sync"
)

// MockAudit is an autogenerated mock type for the Audit type
type MockAudit struct {
	mock.Mock
}

type MockAudit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudit) EXPECT() *MockAudit_Expecter {
	return &MockAudit_Expecter{mock: &_m.Mock}
}

// NotifyAll provides a mock function with given fields: event
func (_m *MockAudit) NotifyAll(event models.AuditEvent) *sync.WaitGroup {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for NotifyAll")
	}

	var r0 *sync.WaitGroup
	if rf, ok := ret.Get(0).(func(models.AuditEvent) *sync.WaitGroup); ok {
		r0 = rf(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sync.WaitGroup)
		}
	}

	return r0
}

// MockAudit_NotifyAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyAll'
type MockAudit_NotifyAll_Call struct {
	*mock.Call
}

// NotifyAll is a helper method to define mock.On call
//   - event models.AuditEvent
func (_e *MockAudit_Expecter) NotifyAll(event interface{}) *MockAudit_NotifyAll_Call {
	return &MockAudit_NotifyAll_Call{Call: _e.mock.On("NotifyAll", event)}
}

func (_c *MockAudit_NotifyAll_Call) Run(run func(event models.AuditEvent)) *MockAudit_NotifyAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.AuditEvent))
	})
	return _c
}

func (_c *MockAudit_NotifyAll_Call) Return(_a0 *sync.WaitGroup) *MockAudit_NotifyAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAudit_NotifyAll_Call) RunAndReturn(run func(models.AuditEvent) *sync.WaitGroup) *MockAudit_NotifyAll_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: o
func (_m *MockAudit) Register(o audit.Observer) {
	_m.Called(o)
}

// MockAudit_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAudit_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - o audit.Observer
func (_e *MockAudit_Expecter) Register(o interface{}) *MockAudit_Register_Call {
	return &MockAudit_Register_Call{Call: _e.mock.On("Register", o)}
}

func (_c *MockAudit_Register_Call) Run(run func(o audit.Observer)) *MockAudit_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(audit.Observer))
	})
	return _c
}

func (_c *MockAudit_Register_Call) Return() *MockAudit_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAudit_Register_Call) RunAndReturn(run func(audit.Observer)) *MockAudit_Register_Call {
	_c.Run(run)
	return _c
}

// NewMockAudit creates a new instance of MockAudit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudit {
	mock := &MockAudit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
