// Code generated by reset generator. DO NOT EDIT.

package middlewares

import "compress/gzip"

// Reset resets all fields of compressWriter to their zero values.
func (r *compressWriter) Reset() {
	if r == nil {
		return
	}
	r.w = nil
	if r.zw != nil {
		*r.zw = gzip.Writer{}
	}
	r.compressed = false
	r.wroteHeader = false
}

// Reset resets all fields of compressReader to their zero values.
func (r *compressReader) Reset() {
	if r == nil {
		return
	}
	r.r = nil
	if r.zr != nil {
		*r.zr = gzip.Reader{}
	}
}

// Reset resets all fields of responseData to their zero values.
func (r *responseData) Reset() {
	if r == nil {
		return
	}
	r.status = 0
	r.size = 0
}
