// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlers

import (
	context "context"

	models "github.com/max-marek-projects/shortener/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateShortURL provides a mock function with given fields: ctx, original, scheme, host
func (_m *MockService) CreateShortURL(ctx context.Context, original string, scheme string, host string) (string, error) {
	ret := _m.Called(ctx, original, scheme, host)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, original, scheme, host)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, original, scheme, host)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, original, scheme, host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURL'
type MockService_CreateShortURL_Call struct {
	*mock.Call
}

// CreateShortURL is a helper method to define mock.On call
//   - ctx context.Context
//   - original string
//   - scheme string
//   - host string
func (_e *MockService_Expecter) CreateShortURL(ctx interface{}, original interface{}, scheme interface{}, host interface{}) *MockService_CreateShortURL_Call {
	return &MockService_CreateShortURL_Call{Call: _e.mock.On("CreateShortURL", ctx, original, scheme, host)}
}

func (_c *MockService_CreateShortURL_Call) Run(run func(ctx context.Context, original string, scheme string, host string)) *MockService_CreateShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_CreateShortURL_Call) Return(_a0 string, _a1 error) *MockService_CreateShortURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateShortURL_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockService_CreateShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShortURLsBatch provides a mock function with given fields: ctx, req, scheme, host
func (_m *MockService) CreateShortURLsBatch(ctx context.Context, req []models.BatchShortenRequest, scheme string, host string) ([]models.BatchShortenResponse, error) {
	ret := _m.Called(ctx, req, scheme, host)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURLsBatch")
	}

	var r0 []models.BatchShortenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.BatchShortenRequest, string, string) ([]models.BatchShortenResponse, error)); ok {
		return rf(ctx, req, scheme, host)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.BatchShortenRequest, string, string) []models.BatchShortenResponse); ok {
		r0 = rf(ctx, req, scheme, host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BatchShortenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.BatchShortenRequest, string, string) error); ok {
		r1 = rf(ctx, req, scheme, host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateShortURLsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURLsBatch'
type MockService_CreateShortURLsBatch_Call struct {
	*mock.Call
}

// CreateShortURLsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req []models.BatchShortenRequest
//   - scheme string
//   - host string
func (_e *MockService_Expecter) CreateShortURLsBatch(ctx interface{}, req interface{}, scheme interface{}, host interface{}) *MockService_CreateShortURLsBatch_Call {
	return &MockService_CreateShortURLsBatch_Call{Call: _e.mock.On("CreateShortURLsBatch", ctx, req, scheme, host)}
}

func (_c *MockService_CreateShortURLsBatch_Call) Run(run func(ctx context.Context, req []models.BatchShortenRequest, scheme string, host string)) *MockService_CreateShortURLsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.BatchShortenRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_CreateShortURLsBatch_Call) Return(_a0 []models.BatchShortenResponse, _a1 error) *MockService_CreateShortURLsBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateShortURLsBatch_Call) RunAndReturn(run func(context.Context, []models.BatchShortenRequest, string, string) ([]models.BatchShortenResponse, error)) *MockService_CreateShortURLsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserURLs provides a mock function with given fields: ctx, userID, shortIDs
func (_m *MockService) DeleteUserURLs(ctx context.Context, userID string, shortIDs []string) error {
	ret := _m.Called(ctx, userID, shortIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserURLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, userID, shortIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserURLs'
type MockService_DeleteUserURLs_Call struct {
	*mock.Call
}

// DeleteUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - shortIDs []string
func (_e *MockService_Expecter) DeleteUserURLs(ctx interface{}, userID interface{}, shortIDs interface{}) *MockService_DeleteUserURLs_Call {
	return &MockService_DeleteUserURLs_Call{Call: _e.mock.On("DeleteUserURLs", ctx, userID, shortIDs)}
}

func (_c *MockService_DeleteUserURLs_Call) Run(run func(ctx context.Context, userID string, shortIDs []string)) *MockService_DeleteUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockService_DeleteUserURLs_Call) Return(_a0 error) *MockService_DeleteUserURLs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteUserURLs_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockService_DeleteUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function with given fields: ctx, short
func (_m *MockService) GetOriginalURL(ctx context.Context, short string) (string, error) {
	ret := _m.Called(ctx, short)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, short)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, short)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, short)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type MockService_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - short string
func (_e *MockService_Expecter) GetOriginalURL(ctx interface{}, short interface{}) *MockService_GetOriginalURL_Call {
	return &MockService_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", ctx, short)}
}

func (_c *MockService_GetOriginalURL_Call) Run(run func(ctx context.Context, short string)) *MockService_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetOriginalURL_Call) Return(_a0 string, _a1 error) *MockService_GetOriginalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetOriginalURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockService_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockService) GetStats(ctx context.Context) (models.Statistics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 models.Statistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.Statistics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.Statistics); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.Statistics)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockService_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetStats(ctx interface{}) *MockService_GetStats_Call {
	return &MockService_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockService_GetStats_Call) Run(run func(ctx context.Context)) *MockService_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetStats_Call) Return(_a0 models.Statistics, _a1 error) *MockService_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetStats_Call) RunAndReturn(run func(context.Context) (models.Statistics, error)) *MockService_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function with given fields: ctx, scheme, host
func (_m *MockService) GetUserURLs(ctx context.Context, scheme string, host string) ([]models.UserURL, error) {
	ret := _m.Called(ctx, scheme, host)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []models.UserURL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]models.UserURL, error)); ok {
		return rf(ctx, scheme, host)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []models.UserURL); ok {
		r0 = rf(ctx, scheme, host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserURL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, scheme, host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockService_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - scheme string
//   - host string
func (_e *MockService_Expecter) GetUserURLs(ctx interface{}, scheme interface{}, host interface{}) *MockService_GetUserURLs_Call {
	return &MockService_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, scheme, host)}
}

func (_c *MockService_GetUserURLs_Call) Run(run func(ctx context.Context, scheme string, host string)) *MockService_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetUserURLs_Call) Return(_a0 []models.UserURL, _a1 error) *MockService_GetUserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetUserURLs_Call) RunAndReturn(run func(context.Context, string, string) ([]models.UserURL, error)) *MockService_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockService) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Ping(ctx interface{}) *MockService_Ping_Call {
	return &MockService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockService_Ping_Call) Run(run func(ctx context.Context)) *MockService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Ping_Call) Return(_a0 error) *MockService_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Ping_Call) RunAndReturn(run func(context.Context) error) *MockService_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
