// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/max-marek-projects/shortener/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateShortURL provides a mock function with given fields: ctx, original, scheme, host
func (_m *Service) CreateShortURL(ctx context.Context, original string, scheme string, host string) (string, error) {
	ret := _m.Called(ctx, original, scheme, host)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, original, scheme, host)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, original, scheme, host)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, original, scheme, host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURL'
type Service_CreateShortURL_Call struct {
	*mock.Call
}

// CreateShortURL is a helper method to define mock.On call
//   - ctx context.Context
//   - original string
//   - scheme string
//   - host string
func (_e *Service_Expecter) CreateShortURL(ctx interface{}, original interface{}, scheme interface{}, host interface{}) *Service_CreateShortURL_Call {
	return &Service_CreateShortURL_Call{Call: _e.mock.On("CreateShortURL", ctx, original, scheme, host)}
}

func (_c *Service_CreateShortURL_Call) Run(run func(ctx context.Context, original string, scheme string, host string)) *Service_CreateShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Service_CreateShortURL_Call) Return(_a0 string, _a1 error) *Service_CreateShortURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateShortURL_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *Service_CreateShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShortURLsBatch provides a mock function with given fields: ctx, req, scheme, host
func (_m *Service) CreateShortURLsBatch(ctx context.Context, req []models.BatchShortenRequest, scheme string, host string) ([]models.BatchShortenResponse, error) {
	ret := _m.Called(ctx, req, scheme, host)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURLsBatch")
	}

	var r0 []models.BatchShortenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.BatchShortenRequest, string, string) ([]models.BatchShortenResponse, error)); ok {
		return rf(ctx, req, scheme, host)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.BatchShortenRequest, string, string) []models.BatchShortenResponse); ok {
		r0 = rf(ctx, req, scheme, host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BatchShortenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.BatchShortenRequest, string, string) error); ok {
		r1 = rf(ctx, req, scheme, host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateShortURLsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURLsBatch'
type Service_CreateShortURLsBatch_Call struct {
	*mock.Call
}

// CreateShortURLsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req []models.BatchShortenRequest
//   - scheme string
//   - host string
func (_e *Service_Expecter) CreateShortURLsBatch(ctx interface{}, req interface{}, scheme interface{}, host interface{}) *Service_CreateShortURLsBatch_Call {
	return &Service_CreateShortURLsBatch_Call{Call: _e.mock.On("CreateShortURLsBatch", ctx, req, scheme, host)}
}

func (_c *Service_CreateShortURLsBatch_Call) Run(run func(ctx context.Context, req []models.BatchShortenRequest, scheme string, host string)) *Service_CreateShortURLsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.BatchShortenRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Service_CreateShortURLsBatch_Call) Return(_a0 []models.BatchShortenResponse, _a1 error) *Service_CreateShortURLsBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateShortURLsBatch_Call) RunAndReturn(run func(context.Context, []models.BatchShortenRequest, string, string) ([]models.BatchShortenResponse, error)) *Service_CreateShortURLsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function with given fields: ctx, short
func (_m *Service) GetOriginalURL(ctx context.Context, short string) (string, error) {
	ret := _m.Called(ctx, short)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, short)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, short)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, short)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type Service_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - short string
func (_e *Service_Expecter) GetOriginalURL(ctx interface{}, short interface{}) *Service_GetOriginalURL_Call {
	return &Service_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", ctx, short)}
}

func (_c *Service_GetOriginalURL_Call) Run(run func(ctx context.Context, short string)) *Service_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetOriginalURL_Call) Return(_a0 string, _a1 error) *Service_GetOriginalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetOriginalURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Service_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *Service) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Service_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) Ping(ctx interface{}) *Service_Ping_Call {
	return &Service_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *Service_Ping_Call) Run(run func(ctx context.Context)) *Service_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_Ping_Call) Return(_a0 error) *Service_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Ping_Call) RunAndReturn(run func(context.Context) error) *Service_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
